import { describe, expect, it } from "vitest";
import {
    DiagnosticCode,
    emitHlsl,
    parseShaderGraphDocument,
    parseSurfaceProfileDescriptor,
} from "../src/index.js";
import type { HlslEmission, SurfaceProfileDescriptor } from "../src/index.js";
import { canonicalV1Fixture } from "./fixtures/descriptor-v1.js";

const parsedDescriptor = parseSurfaceProfileDescriptor(JSON.stringify(canonicalV1Fixture));
if (parsedDescriptor.value === null) {
    throw new Error("expected the canonical v1 descriptor fixture to parse");
}
const descriptor: SurfaceProfileDescriptor = parsedDescriptor.value;

function baseDocument(): Record<string, unknown> {
    return {
        schemaVersion: 1,
        graphId: "graph.emit",
        profile: "gglab.surface",
        profileVersion: 1,
        parameters: [
            { id: "p.tint", name: "Tint", class: "VectorParameter" },
            { id: "p.metal", name: "Metal Factor", class: "ScalarParameter" },
        ],
        nodes: [
            { id: "n.t", type: "VectorParameter", version: 1, properties: { parameterId: "p.tint" } },
            { id: "n.sf", type: "ScalarParameter", version: 1, properties: { parameterId: "p.metal" } },
            { id: "n.c", type: "Float3", version: 1, properties: { value: [1, 1, 1] } },
            { id: "n.r", type: "Float", version: 1, properties: { value: 0.5 } },
            { id: "n.o", type: "Float", version: 1, properties: { value: 1 } },
            { id: "n.out", type: "SurfaceOutput", version: 1, properties: {} },
        ],
        connections: [
            { id: "c1", from: { nodeId: "n.t", portId: "value" }, to: { nodeId: "n.out", portId: "Emissive" } },
            { id: "c2", from: { nodeId: "n.c", portId: "value" }, to: { nodeId: "n.out", portId: "BaseColor" } },
            { id: "c3", from: { nodeId: "n.sf", portId: "value" }, to: { nodeId: "n.out", portId: "Metallic" } },
            { id: "c4", from: { nodeId: "n.r", portId: "value" }, to: { nodeId: "n.out", portId: "Roughness" } },
            { id: "c5", from: { nodeId: "n.o", portId: "value" }, to: { nodeId: "n.out", portId: "Opacity" } },
        ],
        editorMetadata: { nodes: {} },
    };
}

const baseJson = JSON.stringify(baseDocument());

function emitParsed(raw: string): HlslEmission {
    const parsed = parseShaderGraphDocument(raw);
    if (!parsed.ok || parsed.value === null) {
        throw new Error(`expected a parseable document: ${JSON.stringify(parsed.diagnostics)}`);
    }
    return emitHlsl(parsed.value, descriptor);
}

function emitVariant(mutate: (document: Record<string, unknown>) => void): HlslEmission {
    const document: Record<string, unknown> = JSON.parse(baseJson);
    mutate(document);
    return emitParsed(JSON.stringify(document));
}

function expectElement<T>(elements: readonly T[], index: number): T {
    const element = elements[index];
    if (element === undefined) {
        throw new Error(`expected element ${index} to exist in [${elements.length}]`);
    }
    return element;
}

describe("emitHlsl", () => {
    it("emits the frozen contract shape for a numeric surface document, byte-for-byte", () => {
        const result = emitParsed(baseJson);
        expect(result.ok).toBe(true);
        expect(result.diagnostics).toEqual([]);
        expect(result.source).toBe(
            [
                "// Generated by GGLab ShaderGraphCore. Do not edit; regenerate from the source .shadergraph document.",
                "",
                "struct SurfaceData",
                "{",
                "    float3 BaseColor;",
                "    float3 Emissive;",
                "    float Metallic;",
                "    float Roughness;",
                "    float Opacity;",
                "};",
                "",
                "SurfaceData EvaluateSurface(",
                "    float3 gglab_p_tint,",
                "    float gglab_p_metal,",
                "    float2 gglab_uv0",
                ")",
                "{",
                "    SurfaceData surface;",
                "    float3 v_n_c = float3(1.0, 1.0, 1.0);",
                "    float v_n_o = 1.0;",
                "    float v_n_r = 0.5;",
                "    float v_n_sf = gglab_p_metal;",
                "    float3 v_n_t = gglab_p_tint;",
                "    surface.BaseColor = v_n_c;",
                "    surface.Emissive = v_n_t;",
                "    surface.Metallic = v_n_sf;",
                "    surface.Roughness = v_n_r;",
                "    surface.Opacity = v_n_o;",
                "    return surface;",
                "}",
                "",
            ].join("\n"),
        );
    });

    it("is byte-stable under incidental array order", () => {
        const reference = emitParsed(baseJson);
        expect(reference.ok).toBe(true);
        const variant = (nodeOrder: "keep" | "reverse", connectionOrder: "keep" | "reverse"): HlslEmission => {
            const raw = JSON.parse(baseJson) as Record<string, unknown>;
            if (nodeOrder === "reverse") {
                raw["nodes"] = [...(raw["nodes"] as unknown[])].reverse();
            }
            if (connectionOrder === "reverse") {
                raw["connections"] = [...(raw["connections"] as unknown[])].reverse();
            }
            return emitParsed(JSON.stringify(raw));
        };
        for (const check of [variant("reverse", "keep"), variant("keep", "reverse"), variant("reverse", "reverse")]) {
            expect(check.ok).toBe(true);
            // Byte identity is the strongest form of the deterministic-
            // emission invariant; the SHA-256 durable identity (AGENTS.md)
            // follows from byte identity by definition.
            expect(check.source).toBe(reference.source);
            expect(check.sourceMap).toEqual(reference.sourceMap);
        }
    });

    it("never changes the bytes for display-name-only renames", () => {
        const reference = emitParsed(baseJson);
        const renamed = emitVariant((document) => {
            (document["parameters"] as Record<string, unknown>[]).forEach((parameter) => {
                parameter["name"] = `${parameter["name"]} (renamed)`;
            });
            const nodes = document["nodes"] as Record<string, unknown>[];
            nodes.forEach((node) => {
                node["label"] = `Label ${node["id"]}`;
            });
        });
        expect(renamed.ok).toBe(true);
        expect(renamed.source).toBe(reference.source);
    });

    it("reports an exact source map: spans with a single identity each", () => {
        const result = emitParsed(baseJson);
        const entries = result.sourceMap;
        const source = result.source;
        // 5 node statements + 5 output assignments + 3 signature lines.
        expect(entries).toHaveLength(13);
        let previousEnd = 0;
        for (const entry of entries) {
            expect(entry.start).toBeGreaterThanOrEqual(previousEnd);
            expect(entry.end).toBeGreaterThan(entry.start);
            expect(entry.end).toBeLessThanOrEqual(source.length);
            previousEnd = entry.end;
            let identities = 0;
            if (entry.nodeId !== undefined) {
                identities += 1;
                expect(entry.portId).toBe("value");
            }
            if (entry.parameterId !== undefined) {
                identities += 1;
            }
            if (entry.graphVisibleInputId !== undefined) {
                identities += 1;
            }
            expect(identities).toBe(1);
        }
        const parameterEntry = entries.find((entry) => entry.parameterId === "p.tint");
        expect(parameterEntry).toBeDefined();
        if (parameterEntry !== undefined) {
            expect(source.slice(parameterEntry.start, parameterEntry.end)).toContain("gglab_p_tint");
        }
        const nodeEntry = entries.find((entry) => entry.nodeId === "n.m");
        expect(nodeEntry).toBeUndefined();
    });

    it("sanitizes parameter ids to ASCII-safe, collision-free symbols", () => {
        const raw = JSON.parse(baseJson) as Record<string, unknown>;
        const parameters = raw["parameters"] as Record<string, unknown>[];
        const nodes = raw["nodes"] as Record<string, unknown>[];
        // Rename the parameter ids and the node references that name them.
        expectElement(parameters, 0)["id"] = "a.b";
        expectElement(parameters, 1)["id"] = "a_b";
        (nodes.find((node) => node["id"] === "n.t") as Record<string, unknown>)["properties"] = { parameterId: "a.b" };
        (nodes.find((node) => node["id"] === "n.sf") as Record<string, unknown>)["properties"] = { parameterId: "a_b" };
        const result = emitParsed(JSON.stringify(raw));
        expect(result.ok).toBe(true);
        const source = result.source;
        expect(source).toContain("gglab_a_b");
        expect(source).toContain("gglab_a_b_2");
        // Each symbol appears on its signature line and its node statement.
        const symbolMatches = [...new Set(source.match(/\bgglab_a_b(_2)?\b/g) ?? [])];
        expect(symbolMatches).toEqual(["gglab_a_b", "gglab_a_b_2"]);
    });

    it("rejects mixed vector sizes meeting in a math operation", () => {
        const document: Record<string, unknown> = {
            schemaVersion: 1,
            graphId: "graph.mixed",
            profile: "gglab.surface",
            profileVersion: 1,
            parameters: [{ id: "p.metal", name: "M", class: "ScalarParameter" }],
            nodes: [
                { id: "n.f2", type: "Float2", version: 1, properties: { value: [1, 1] } },
                { id: "n.f3", type: "Float3", version: 1, properties: { value: [1, 1, 1] } },
                { id: "n.m", type: "Multiply", version: 1, properties: {} },
                { id: "n.e", type: "Float3", version: 1, properties: { value: [0, 0, 0] } },
                { id: "n.sf", type: "ScalarParameter", version: 1, properties: { parameterId: "p.metal" } },
                { id: "n.r", type: "Float", version: 1, properties: { value: 0.5 } },
                { id: "n.o", type: "Float", version: 1, properties: { value: 1 } },
                { id: "n.out", type: "SurfaceOutput", version: 1, properties: {} },
            ],
            connections: [
                { id: "c1", from: { nodeId: "n.f2", portId: "value" }, to: { nodeId: "n.m", portId: "a" } },
                { id: "c2", from: { nodeId: "n.f3", portId: "value" }, to: { nodeId: "n.m", portId: "b" } },
                { id: "c3", from: { nodeId: "n.m", portId: "value" }, to: { nodeId: "n.out", portId: "BaseColor" } },
                { id: "c4", from: { nodeId: "n.e", portId: "value" }, to: { nodeId: "n.out", portId: "Emissive" } },
                { id: "c5", from: { nodeId: "n.sf", portId: "value" }, to: { nodeId: "n.out", portId: "Metallic" } },
                { id: "c6", from: { nodeId: "n.r", portId: "value" }, to: { nodeId: "n.out", portId: "Roughness" } },
                { id: "c7", from: { nodeId: "n.o", portId: "value" }, to: { nodeId: "n.out", portId: "Opacity" } },
            ],
            editorMetadata: { nodes: {} },
        };
        const result = emitParsed(JSON.stringify(document));
        expect(result.ok).toBe(false);
        expect(result.source).toBe("");
        expect(result.diagnostics).toEqual([
            expect.objectContaining({ code: DiagnosticCode.TypeMismatch, severity: "error", dataPath: "$.nodes[2]" }),
        ]);
    });

    it("refuses a parameter class in the descriptor's deferred set", () => {
        const result = emitVariant((document) => {
            const parameters = document["parameters"] as Record<string, unknown>[];
            expectElement(parameters, 1)["class"] = "BoolParameter";
        });
        expect(result.ok).toBe(false);
        expect(result.source).toBe("");
        expect(result.diagnostics).toEqual([
            expect.objectContaining({
                code: DiagnosticCode.UnsupportedParameterClass,
                severity: "error",
                dataPath: "$.parameters[1]",
                message: expect.stringContaining("deferred"),
            }),
        ]);
    });

    it("refuses texture sampling nodes with a structured diagnostic", () => {
        const document: Record<string, unknown> = {
            schemaVersion: 1,
            graphId: "graph.texture",
            profile: "gglab.surface",
            profileVersion: 1,
            parameters: [{ id: "p.tex", name: "Texture", class: "Texture2DParameter" }],
            nodes: [
                { id: "n.tp", type: "Texture2DParameter", version: 1, properties: { parameterId: "p.tex" } },
                { id: "n.uv", type: "UV0", version: 1, properties: {} },
                { id: "n.smp", type: "SampleTexture2D", version: 1, properties: {} },
                { id: "n.e", type: "Float3", version: 1, properties: { value: [0, 0, 0] } },
                { id: "n.r", type: "Float", version: 1, properties: { value: 0.5 } },
                { id: "n.o", type: "Float", version: 1, properties: { value: 1 } },
                { id: "n.out", type: "SurfaceOutput", version: 1, properties: {} },
            ],
            connections: [
                { id: "c1", from: { nodeId: "n.tp", portId: "value" }, to: { nodeId: "n.smp", portId: "texture" } },
                { id: "c2", from: { nodeId: "n.uv", portId: "value" }, to: { nodeId: "n.smp", portId: "uv" } },
                { id: "c3", from: { nodeId: "n.smp", portId: "RGB" }, to: { nodeId: "n.out", portId: "BaseColor" } },
                { id: "c4", from: { nodeId: "n.smp", portId: "R" }, to: { nodeId: "n.out", portId: "Metallic" } },
                { id: "c5", from: { nodeId: "n.e", portId: "value" }, to: { nodeId: "n.out", portId: "Emissive" } },
                { id: "c6", from: { nodeId: "n.r", portId: "value" }, to: { nodeId: "n.out", portId: "Roughness" } },
                { id: "c7", from: { nodeId: "n.o", portId: "value" }, to: { nodeId: "n.out", portId: "Opacity" } },
            ],
            editorMetadata: { nodes: {} },
        };
        const result = emitParsed(JSON.stringify(document));
        expect(result.ok).toBe(false);
        expect(result.source).toBe("");
        // Topological order visits the texture parameter before the sampler.
        expect(result.diagnostics).toEqual([
            expect.objectContaining({
                code: DiagnosticCode.UnsupportedNodeEmission,
                severity: "error",
                dataPath: "$.nodes[0]",
                message: expect.stringContaining("texture-sampling"),
            }),
            expect.objectContaining({
                code: DiagnosticCode.UnsupportedNodeEmission,
                severity: "error",
                dataPath: "$.nodes[2]",
                message: expect.stringContaining("texture-sampling"),
            }),
        ]);
    });

    it("propagates validation failures without emitting", () => {
        const result = emitVariant((document) => {
            document["connections"] = (document["connections"] as Record<string, unknown>[]).filter(
                (connection) => connection["id"] !== "c4",
            );
        });
        expect(result.ok).toBe(false);
        expect(result.source).toBe("");
        expect(result.diagnostics).toContainEqual(
            expect.objectContaining({ code: DiagnosticCode.MissingRequiredInput, severity: "error" }),
        );
    });

    it("refuses a vector parameter whose usage does not fix a single concrete type", () => {
        const document: Record<string, unknown> = {
            schemaVersion: 1,
            graphId: "graph.ambiguous",
            profile: "gglab.surface",
            profileVersion: 1,
            parameters: [
                { id: "p.tint", name: "Tint", class: "VectorParameter" },
                { id: "p.metal", name: "M", class: "ScalarParameter" },
            ],
            nodes: [
                { id: "n.t", type: "VectorParameter", version: 1, properties: { parameterId: "p.tint" } },
                { id: "n.mf", type: "Multiply", version: 1, properties: {} },
                { id: "n.f2", type: "Float2", version: 1, properties: { value: [1, 1] } },
                { id: "n.e", type: "Float3", version: 1, properties: { value: [0, 0, 0] } },
                { id: "n.sf", type: "ScalarParameter", version: 1, properties: { parameterId: "p.metal" } },
                { id: "n.r", type: "Float", version: 1, properties: { value: 0.5 } },
                { id: "n.o", type: "Float", version: 1, properties: { value: 1 } },
                { id: "n.out", type: "SurfaceOutput", version: 1, properties: {} },
            ],
            connections: [
                { id: "c1", from: { nodeId: "n.t", portId: "value" }, to: { nodeId: "n.mf", portId: "a" } },
                { id: "c2", from: { nodeId: "n.f2", portId: "value" }, to: { nodeId: "n.mf", portId: "b" } },
                { id: "c3", from: { nodeId: "n.mf", portId: "value" }, to: { nodeId: "n.out", portId: "BaseColor" } },
                { id: "c4", from: { nodeId: "n.t", portId: "value" }, to: { nodeId: "n.out", portId: "Emissive" } },
                { id: "c5", from: { nodeId: "n.sf", portId: "value" }, to: { nodeId: "n.out", portId: "Metallic" } },
                { id: "c6", from: { nodeId: "n.r", portId: "value" }, to: { nodeId: "n.out", portId: "Roughness" } },
                { id: "c7", from: { nodeId: "n.o", portId: "value" }, to: { nodeId: "n.out", portId: "Opacity" } },
            ],
            editorMetadata: { nodes: {} },
        };
        const result = emitParsed(JSON.stringify(document));
        expect(result.ok).toBe(false);
        expect(result.source).toBe("");
        expect(result.diagnostics).toEqual([
            expect.objectContaining({
                code: DiagnosticCode.AmbiguousParameterType,
                severity: "error",
                dataPath: "$.parameters[0]",
            }),
        ]);
    });

    it("reports a second output node as an ambiguous output root", () => {
        const result = emitVariant((document) => {
            (document["nodes"] as Record<string, unknown>[]).push({ id: "n.out2", type: "SurfaceOutput", version: 1, properties: {} });
            const connections = document["connections"] as Record<string, unknown>[];
            connections.forEach((connection) => {
                const target = (connection["to"] as Record<string, unknown>)["nodeId"];
                if (target === "n.out") {
                    connections.push({
                        id: `${connection["id"]}_2`,
                        from: connection["from"],
                        to: { nodeId: "n.out2", portId: (connection["to"] as Record<string, unknown>)["portId"] },
                    });
                }
            });
        });
        expect(result.ok).toBe(false);
        expect(result.diagnostics).toEqual([
            expect.objectContaining({ code: DiagnosticCode.AmbiguousOutputRoot, severity: "error", dataPath: "$" }),
        ]);
    });

    it("rejects a descriptor whose profile does not match the document", () => {
        const result = emitVariant((document) => {
            document["profile"] = "gglab.fresnel";
        });
        expect(result.ok).toBe(false);
        expect(result.diagnostics).toEqual([
            expect.objectContaining({ code: DiagnosticCode.ProfileMismatch, severity: "error", dataPath: "$" }),
        ]);
    });

    it("propagates topology cycle failures", () => {
        const document: Record<string, unknown> = {
            schemaVersion: 1,
            graphId: "graph.cycle-emit",
            profile: "gglab.surface",
            profileVersion: 1,
            parameters: [],
            nodes: [
                { id: "n.a", type: "Saturate", version: 1, properties: {} },
                { id: "n.b", type: "Saturate", version: 1, properties: {} },
                { id: "n.out", type: "SurfaceOutput", version: 1, properties: {} },
            ],
            connections: [
                { id: "c1", from: { nodeId: "n.b", portId: "value" }, to: { nodeId: "n.a", portId: "value" } },
                { id: "c2", from: { nodeId: "n.a", portId: "value" }, to: { nodeId: "n.b", portId: "value" } },
                { id: "c3", from: { nodeId: "n.a", portId: "value" }, to: { nodeId: "n.out", portId: "BaseColor" } },
            ],
            editorMetadata: { nodes: {} },
        };
        const result = emitParsed(JSON.stringify(document));
        expect(result.ok).toBe(false);
        expect(result.source).toBe("");
        // The cycle plus the four unconnected required inputs of the output
        // node are all surfaced by the validation gate.
        expect(result.diagnostics).toHaveLength(5);
        expect(result.diagnostics).toContainEqual(
            expect.objectContaining({ code: DiagnosticCode.CycleDetected, severity: "error" }),
        );
    });
});
