// Generated by GGLab ShaderGraphCore. Do not edit; regenerate from the source .shadergraph document.

struct SurfaceData
{
    float3 BaseColor;
    float3 Emissive;
    float Metallic;
    float Roughness;
    float Opacity;
};

SurfaceData EvaluateSurface(
    float gglab_p_metal,
    float3 gglab_p_tint,
    float2 gglab_uv0
)
{
    SurfaceData surface;
    float3 v_n_c = float3(1.0, 1.0, 1.0);
    float v_n_o = 1.0;
    float v_n_r = 0.5;
    float v_n_sf = gglab_p_metal;
    float3 v_n_t = gglab_p_tint;
    surface.BaseColor = v_n_c;
    surface.Emissive = v_n_t;
    surface.Metallic = v_n_sf;
    surface.Roughness = v_n_r;
    surface.Opacity = v_n_o;
    return surface;
}
