// Generated by GGLab ShaderGraphCore. Do not edit; regenerate from the source .shadergraph document.

struct SurfaceData
{
    float3 BaseColor;
    float3 Emissive;
    float Metallic;
    float Roughness;
    float Opacity;
};

float4 gglab_sampleTexture2D(uint2 textureSamplerBinding, float2 uv0)
{
    Texture2D<float4> texture = ResourceDescriptorHeap[NonUniformResourceIndex(textureSamplerBinding.x)];
    SamplerState sampler = SamplerDescriptorHeap[NonUniformResourceIndex(textureSamplerBinding.y)];
    return texture.Sample(sampler, uv0);
}

SurfaceData EvaluateSurface(
    float gglab_p_rough,
    uint2 gglab_p_tex,
    float2 gglab_uv0
)
{
    SurfaceData surface;
    float3 v_n_e = float3(0.0, 0.0, 0.0);
    float v_n_o = 1.0;
    float v_n_r = gglab_p_rough;
    uint2 v_n_tp = gglab_p_tex;
    float2 v_n_uv = gglab_uv0;
    float4 v_n_smp = gglab_sampleTexture2D(v_n_tp, v_n_uv);
    surface.BaseColor = v_n_smp.rgb;
    surface.Emissive = v_n_e;
    surface.Metallic = v_n_smp.b;
    surface.Roughness = v_n_r;
    surface.Opacity = v_n_o;
    return surface;
}
